version: '3'
services:
  node1:
    image: cassandra:latest
    container_name: node1
    volumes:
      - ./data/node1:/var/lib/cassandra
    ports:
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_SEEDS=node1,node2,node3
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_NUM_TOKENS=256
      # - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=204M
    networks:
      cassandranet:
        ipv4_address: 172.20.0.2

  node2:
    image: cassandra:latest
    container_name: node2
    volumes:
      - ./data/node2:/var/lib/cassandra
    ports:
      - 9043:9042
      - 9161:9160
    environment:
      - CASSANDRA_SEEDS=node1,node2,node3
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_NUM_TOKENS=256
      # - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=204M
    networks:
      cassandranet:
        ipv4_address: 172.20.0.3

  node3:
    image: cassandra:latest
    container_name: node3
    volumes:
      - ./data/node3:/var/lib/cassandra
    ports:
      - 9044:9042
      - 9162:9160
    environment:
      - CASSANDRA_SEEDS=node1,node2,node3
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_NUM_TOKENS=256
      # - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=204M
    networks:
      cassandranet:
        ipv4_address: 172.20.0.4

networks:
  cassandranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
